### ISSUE TITLE
up7 layer's output is not equal to input. 

### ISSUE THREAD

**Issue by ssimine** [nebulaV/DAGAN#3]
Hello, May I ask a problem?
Thank you for your code, I have been learn AI from about 3 weeks ago.
During training, It occur the error above like title.
Help me, please.

up7 = {DeConv2d}   Last layer is: DeConv2d (u_net/deconv7) [25, 2, 2, 512]
 all_drop = {dict} {}
 all_layers = {list} <class 'list'>: [<tf.Tensor 'u_net/conv1/Identity:0' shape=(25, 1, 1, 64) dtype=float32>, <tf.Tensor 'u_net/conv2/Identity:0' shape=(25, 1, 1, 128) dtype=float32>, <tf.Tensor 'u_net/bn2/lrelu:0' shape=(25, 1, 1, 128) dtype=float32>, <tf.Tensor 'u_net/conv3/Identity:0' shape=(25, 1, 1, 256) dtype=float32>, <tf.Tensor 'u_net/bn3/lrelu:0' shape=(25, 1, 1, 256) dtype=float32>, <tf.Tensor 'u_net/conv4/Identity:0' shape=(25, 1, 1, 512) dtype=float32>, <tf.Tensor 'u_net/bn4/lrelu:0' shape=(25, 1, 1, 512) dtype=float32>, <tf.Tensor 'u_net/conv5/Identity:0' shape=(25, 1, 1, 512) dtype=float32>, <tf.Tensor 'u_net/bn5/lrelu:0' shape=(25, 1, 1, 512) dtype=float32>, <tf.Tensor 'u_net/conv6/Identity:0' shape=(25, 1, 1, 512) dtype=float32>, <tf.Tensor 'u_net/bn6/lrelu:0' shape=(25, 1, 1, 512) dtype=float32>, <tf.Tensor 'u_net/conv7/Identity:0' shape=(25, 1, 1, 512) dtype=float32>, <tf.Tensor 'u_net/bn7/lrelu:0' shape=(25, 1, 1, 512) dtype=float32>, <tf.Tensor 'u_net/conv8/lrelu:0' shape=(25, 1, 1, 51...
 all_params = {list} <class 'list'>: [<tf.Variable 'u_net/conv1/kernel:0' shape=(4, 4, 1, 64) dtype=float32_ref>, <tf.Variable 'u_net/conv1/bias:0' shape=(64,) dtype=float32_ref>, <tf.Variable 'u_net/conv2/kernel:0' shape=(4, 4, 64, 128) dtype=float32_ref>, <tf.Variable 'u_net/conv2/bias:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'u_net/bn2/beta:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'u_net/bn2/gamma:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'u_net/bn2/moving_mean:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'u_net/bn2/moving_variance:0' shape=(128,) dtype=float32_ref>, <tf.Variable 'u_net/conv3/kernel:0' shape=(4, 4, 128, 256) dtype=float32_ref>, <tf.Variable 'u_net/conv3/bias:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'u_net/bn3/beta:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'u_net/bn3/gamma:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'u_net/bn3/moving_mean:0' shape=(256,) dtype=float32_ref>, <tf.Variable 'u_net/bn3/moving_variance:0' shape=(256,) dtype=float3...
 # ### 

- inputs = {Tensor} Tensor("u_net/conv8/lrelu:0", **shape=(25, 1, 1, 512)**, dtype=float32)
- name = {str} 'u_net/deconv7'
- outputs = {Tensor} Tensor("u_net/deconv7/Identity:0", **shape=(25, 2, 2, 512)**, dtype=float32)
w_init = {TruncatedNormal} <tensorflow.python.ops.init_ops.TruncatedNormal object at 0x7fd754f26358>
x = {Tensor} Tensor("bad_image:0", shape=(25, 1, 1, 1), dtype=float32)

**Comment by nebulaV** [comment]
What is the shape of your input to the model?

**Comment by ssimine** [comment]
Thank you for your attention. This issue is clear. 
MICCAI13_SegChallenge data-base images was problematic because of its size.
