### ISSUE TITLE
FHD(1920x1080) size image

### ISSUE THREAD

**Issue by ssimine** [nebulaV/DAGAN#4]
Hello. Your paper is very helpful and thankful.
However, I want to learn a bigger size image. I need advice on how to do it.

Can you tell me how to configure the network?

For reference, I am studying to eliminate aliasing of Aliasing images with Aliasing and Ground truth images.

**Comment by nebulaV** [comment]
Hi. Sorry for the delay. I am afraid reconstruction of FHD size images requires careful architectural design and other heuristic tricks. We didn't attempt to do it in this work. Sorry.
